apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: mesh-for-data
  labels:
    project-template: global
spec:
  destinations:
    - namespace: 'm4d-*'
      server: 'https://api.zero.massopen.cloud:6443'
    - namespace: 'mesh-for-data'
      server: 'https://api.zero.massopen.cloud:6443'
  sourceRepos:
    - '*'
  roles:
    - name: project-admin
      description: Read/Write access to this project only
      policies:
        - p, proj:mesh-for-data:project-admin, applications, get, mesh-for-data/*, allow
        - p, proj:mesh-for-data:project-admin, applications, create, mesh-for-data/*, allow
        - p, proj:mesh-for-data:project-admin, applications, update, mesh-for-data/*, allow
        - p, proj:mesh-for-data:project-admin, applications, delete, mesh-for-data/*, allow
        - p, proj:mesh-for-data:project-admin, applications, sync, mesh-for-data/*, allow
        - p, proj:mesh-for-data:project-admin, applications, override, mesh-for-data/*, allow
        - p, proj:mesh-for-data:project-admin, applications, action/*, mesh-for-data/*, allow
      groups:
        - mesh-for-data
        - operate-first
