apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - app-of-apps-curator.yaml
  - app-of-apps-infra.yaml
  - app-of-apps-ocp-prod.yaml
  - app-of-apps-osc-cl1.yaml
  - app-of-apps-rick.yaml
  - app-of-apps-smaug.yaml
  - app-of-apps-zero.yaml
  - workshops-app-of-apps.yaml
