# script `./test-kustomize-build` is contained in the thoth-application/ repo not the opf-toolbox
presubmits:
  - name: kustomize-build
    decorate: true
    max_concurrency: 1
    run_if_changed: ".*yaml"
    skip_report: false
    context: aicoe-ci/prow/kustomize-build
    spec:
      containers:
        - image: quay.io/operate-first/opf-toolbox:v0.2.0
          command:
            - "./test-kustomize-build"
          resources:
            requests:
              memory: "256Mi"
  - name: pre-commit
    decorate: true
    skip_report: false
    always_run: true
    context: aicoe-ci/prow/pre-commit
    spec:
      containers:
        - image: quay.io/thoth-station/thoth-precommit-py38:v0.12.5
          command:
            - "pre-commit"
            - "run"
            - "--all-files"
          resources:
            requests:
              memory: "2Gi"
              cpu: "2"
