apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opf-argo
spec:
  destination:
    namespace: opf-argo
    name: in-cluster
  project: operate-first
  source:
    path: base/argo
    repoURL: https://github.com/operate-first/odh.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - Validate=false
