apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opf-auth
spec:
  destination:
    namespace: opf-auth
    name: in-cluster
  project: operate-first
  source:
    path: auth/base
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
