apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opf-monitoring
spec:
  destination:
    namespace: opf-monitoring
    name: in-cluster
  project: operate-first
  source:
    path: odh/base/monitoring
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
