---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-core-graph
spec:
  project: thoth
  source:
    path: core/overlays/cnv-prod/graph-prod
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    targetRevision: master
  destination:
    namespace: thoth-graph-prod
    server: "https://api.cnv.massopen.cloud:6443"
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
