---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-package-update
spec:
  project: thoth
  source:
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    path: package-update/overlays/cnv-prod
    targetRevision: HEAD
  destination:
    server: "https://api.cnv.massopen.cloud:6443"
    namespace: thoth-frontend-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
