---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-elyra-aidevsecops-tutorial
spec:
  project: thoth
  source:
    repoURL: "https://github.com/thoth-station/elyra-aidevsecops-tutorial.git"
    path: elyra-aidevsecops-tutorial/manifests/overlays/test
    targetRevision: master
  destination:
    server: "https://kubernetes.default.svc"
    namespace: thoth-deployment-examples
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
