---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-amun-api
spec:
  project: thoth
  source:
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    path: amun/overlays/cnv-prod/amun-api
    targetRevision: HEAD
  destination:
    server: "https://api.cnv.massopen.cloud:6443"
    namespace: thoth-amun-api-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
