---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-sefkhet-abwy
spec:
  project: thoth
  source:
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    path: sefkhet-abwy/overlays/cnv-prod
    targetRevision: master
  destination:
    server: "https://kubernetes.default.svc"
    namespace: thoth-bots-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
  ignoreDifferences:
    - group: batch
      kind: CronJob
      name: new-label-normalizer-aicoe
      jsonPointers:
        - /spec/template/spec/containers/0/image
    - group: batch
      kind: CronJob
      name: new-label-normalizer-thoth-station
      jsonPointers:
        - /spec/template/spec/containers/0/image
