---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-mi
spec:
  project: thoth
  source:
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    path: mi-scheduler/overlays/cnv-prod
    targetRevision: master
  destination:
    server: "https://api.cnv.massopen.cloud:6443"
    namespace: thoth-middletier-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
