---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-package-releases
spec:
  project: thoth
  source:
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    path: package-releases/overlays/cnv-prod
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: thoth-frontend-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
