---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-solver
spec:
  project: thoth
  source:
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    path: solver/overlays/cnv-prod
    targetRevision: master
  destination:
    server: "https://kubernetes.default.svc"
    namespace: thoth-middletier-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
