---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-core-infra
spec:
  project: thoth
  source:
    path: core/overlays/cnv-prod/infra-prod
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    targetRevision: master
  destination:
    namespace: thoth-infra-prod
    name: moc-cnv
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
