---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-core-middletier
spec:
  project: thoth
  source:
    path: core/overlays/cnv-prod/middletier-prod
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    targetRevision: master
  destination:
    namespace: thoth-middletier-prod
    name: zero
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
