---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-triage-party
spec:
  project: thoth
  source:
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    path: triage-party/overlays/zero-prod
    targetRevision: master
  destination:
    name: zero
    namespace: thoth-bots-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
