---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-purge-job
spec:
  project: thoth
  source:
    repoURL: 'https://github.com/thoth-station/thoth-application.git'
    path: purge-job/overlays/cnv-prod
    targetRevision: master
  destination:
    name: zero
    namespace: thoth-middletier-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
