---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-graph-metrics-exporter
spec:
  project: thoth
  source:
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    path: graph-metrics-exporter/overlays/cnv-prod
    targetRevision: master
  destination:
    name: zero
    namespace: thoth-graph-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
