---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-revsolver
spec:
  project: thoth
  source:
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    path: revsolver/overlays/cnv-prod
    targetRevision: HEAD
  destination:
    name: zero
    namespace: thoth-middletier-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
