---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-prescription-sync
spec:
  project: thoth
  source:
    repoURL: 'https://github.com/thoth-station/thoth-application.git'
    path: prescription-sync-job/overlays/cnv-prod
    targetRevision: master
  destination:
    name: zero
    namespace: thoth-backend-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
    - group: batch
      kind: CronJob
      jsonPointers:
        - /spec/jobTemplate/spec/template/spec/containers/0/image
