---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-slo-reporter
spec:
  project: thoth
  source:
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    path: slo-reporter/overlays/cnv-prod
    targetRevision: master
  destination:
    name: zero
    namespace: thoth-infra-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
  ignoreDifferences:
    - group: batch
      kind: CronJob
      name: slo-reporter
      jsonPointers:
        - /spec/jobTemplate/spec/template/spec/containers/0/image
