---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-thoth-adviser
spec:
  project: thoth
  source:
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    path: adviser/overlays/cnv-prod
    targetRevision: master
  destination:
    name: zero
    namespace: thoth-backend-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - Validate=false
