---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-prow-prod
spec:
  project: operate-first
  source:
    path: prow/overlays/cnv-prod
    repoURL: "https://github.com/thoth-station/thoth-application.git"
    targetRevision: master
  destination:
    namespace: opf-ci-prow
    server: "https://kubernetes.default.svc"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/template/spec/containers/0/image
