---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opf-kafka
spec:
  destination:
    name: zero
    namespace: opf-kafka
  project: operate-first
  source:
    path: odh/overlays/moc/zero/kafka
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=false
