---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opf-slack-first
spec:
  destination:
    name: zero
    namespace: opf-slack-first
  project: operate-first
  source:
    path: slack-first/overlays/moc/zero
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
