apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-resources-infra
spec:
  destination:
    name: moc-infra
    namespace: argocd
  project: cluster-management
  source:
    path: cluster-scope/overlays/moc-infra/
    repoURL: https://github.com/operate-first/apps.git
    targetRevision: HEAD
