apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-cicd-app-of-apps
spec:
  destination:
    name: moc-infra
    namespace: argocd
  project: operate-first
  source:
    path: lab-cicd
    repoURL: https://github.com/operate-first/workshop-apps.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
